baseURL = "https://bellaeloy.github.io/"
title = "Isabella Cavalcanti"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
pagination.pagerSize = 20

enableEmoji = true
builddrafts = false

[params]
author = "Isabella Cavalcanti"
description = "Architect and urban designer. Parametric modeling, urban development research and civic data."
keywords = "architecture,urban design,urbanism,parametric modeling,grasshopper,portfolio"
info = ["Urban data analyst, designer and researcher", "Passionate about understanding cities through data, technology, and design."]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2006"
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

customCSS = []
customSCSS = ["scss/custom.scss"]
customJS = []
customRemoteJS = []

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/bellaeloy/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/isabella-eloy/"

[[params.social]]
name = "ORCID"
icon = "fa fa-2x fa-id-badge"
weight = 3
url = "https://orcid.org/0000-0002-6462-5849"

[[params.social]]
name = "Lattes"
icon = "fa fa-2x fa-graduation-cap"
weight = 4
url = "http://lattes.cnpq.br/0165490242445275"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 5
url = "mailto:isabellaeloy.be@gmail.com"

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Timeline"
weight = 2
url = "timeline/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Artwork"
weight = 4
url = "artwork/"

[[languages.en.menu.main]]
name = "Resume/CV"
weight = 5
url = "resume.pdf"
